apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-auth
  namespace: gallery
spec:
  serviceName: "postgres-auth"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          envFrom:
            - configMapRef:
                name: postgres-auth-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_AUTH_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_AUTH_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata-auth
              mountPath: /var/lib/postgresql
          resources:
            requests:
              memory: "250M"
              cpu: "100m"
            limits:
              memory: "500M"
              cpu: "500m"
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: pgdata-auth
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi