apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: gallery
type: Opaque
stringData:
  POSTGRES_COMMENTS_USER: "testUser"
  POSTGRES_COMMENTS_PASSWORD: "testPassword"
  POSTGRES_IMAGES_USER: "testUser"
  POSTGRES_IMAGES_PASSWORD: "testPassword"
  POSTGRES_AUTH_USER: "testUser"
  POSTGRES_AUTH_PASSWORD: "testPassword"
  POSTGRES_USERS_USER: "testUser"
  POSTGRES_USERS_PASSWORD: "testPassword"
