apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: gallery
type: Opaque
stringData:
  REDIS_USER: "testRedisUser"
  REDIS_PASSWORD: "testRedisUserPassword"
  REDIS_DEFAULT_PASSWORD: "testRedisPassword"