apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
  namespace: gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      labels:
        app: activity-service
    spec:
      containers:
        - name: activity-service
          image: lubospodkidos/gallery-activity-service:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: activity-env
          resources:
            requests:
              memory: "350M"
              cpu: "100m"
            limits:
              memory: "700M"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3