apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: lubospodkidos/gallery-auth-service:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: auth-env
          env:
            - name: AUTHENTICATION_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_AUTH_USER
            - name: AUTHENTICATION_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_AUTH_PASSWORD
          volumeMounts:
            - name: private-keys
              mountPath: /app/certs
              readOnly: true
          resources:
            requests:
              memory: "250M"
              cpu: "100m"
            limits:
              memory: "500M"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3

      volumes:
        - name: private-keys
          secret:
            secretName: auth-keys-secret