apiVersion: v1
kind: Secret
metadata:
  name: auth-keys-secret
  namespace: gallery
type: Opaque
stringData:
  auth-server.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFLjCCAxagAwIBAgIUUODpVT537eeoxOqT6mz8xyS07LcwDQYJKoZIhvcNAQEL
    BQAwIDEeMBwGA1UEAwwVQXV0aGVudGljYXRpb24gU2VydmVyMB4XDTI1MTIyNDEy
    NTg0N1oXDTI4MTAxMzEyNTg0N1owIDEeMBwGA1UEAwwVQXV0aGVudGljYXRpb24g
    U2VydmVyMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0zOVigR69+XA
    nEuCMreVNEAahiNqo1S8tCIQ7pHSqWaInS8fGbpPNcc3wEEYSlgfsffbQBhTFC4I
    PW/+IzIlN3HdrVIyn7JuN7PC9P/gJb6Qgp1nwmXXvEcDfpIR7efPo1laMvCowzCo
    HyhqOlHorNYwWuWkFICQhoiqmchVTiCD54ca9+bG9AJBpL75b9eevECFWS4flt+W
    KG0jr1SrVE7046yYq6XlANWhG/FxEUFYQzB+Uev4ICQ+Ji5HfTesC/RFBXHyWoVC
    j8rt6QCuhaWU61TjLSL7bhW4n5fTdQr+asPW7CxtCwvUExieZfnemiRls6tdex3e
    7BTGhbdgSrOpEL0Ltk9w/Ca/vLlu1yk4eJ8F+8qDp4BCWtYGDIVHK9mWg1Zt/iB1
    flKqZkA7MEqF+M99I4nRon96HXVPUOLQXVp398cGuIJ7hrJD1sYnXJ9srIW9Wy6i
    HCqDFzUzKZkqnWXftLCt09Fy/02VSDfjH4x2WXZDRBS2nJJKhGaKjYmAcoJRwQFo
    rioCsxa5HJ1b26woQ1y5Z63mpVD7vZ39sRVtjsl6rbkfQToXfphALef34QTlihtE
    8xNVVFXF0zLg320dRs/UIyoGkCxMMW7COfRu3hcegcmEclOCjghioPXTUNz8k2Ko
    OXcI6UJsZeWmuIJx8g18G8Nb1lsuf90CAwEAAaNgMF4wHwYDVR0jBBgwFoAUUlp2
    UBaMr3Vl1klmO1GX6yQliOgwDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4Aw
    HQYDVR0OBBYEFFJadlAWjK91ZdZJZjtRl+skJYjoMA0GCSqGSIb3DQEBCwUAA4IC
    AQBX40EwyDeaiMR6GwNzWQzuOrveQ90X8S17LqaeCiGliHN06G4Ok3tuE2ldoGjl
    s7trggnNq3BgGZPVpPdoQo1gA0NmdyJUuUiLeVCL9bmBHg/RydIgdsVAzttEhajP
    l8NYBVu67kwWUBqsXI422bavtHUwSkZEL5ChYxFA45/OZCmv+PYrSpcEUUzTi7RL
    G2e2h7YbfQ8DaVNpKQf0qgFRc+4W5M7zcnE9SGD4yyEjPoBpBDp9TlU0j4GORD2H
    ZdrhOVi6ICxNqU9uu9x8Hm4LbuSsBKBkFSV2vJkCQaKV6jqi8EPz/LKNgceGDfV9
    2/oV0DRIIKfFpd0kc89Ns8nvMAeODXgBPaQ5pVpSONhGZcwGr2LttmRLTUQu4sdu
    UdKJ51Y8vAJIHzRBNp4M18J6QbBnegqQE9MeCl4EjddcEMCZwFMLw6fVvB1uoo6y
    kSMjMRluzYRdu38CR4iqlVHj/hARp7feVEwTCcO2uGyGLtO1t7we86Szq6E3TOpY
    /cJPKw5dgKIxYrgOsbcItJprsIgQXpC02PRVVgDKkn+rt90lt0tA4Y09hl7Irljq
    6zGg1XDJAbEO9B2NM5Uyj7wqtYE5M92Z8B6/Gw3LgE54gAdVQGkpxQSlDVEKHUIA
    uhJoGixBqMa0lyiFhH9HcoyBQIqTJ1SWJOA4cizjIdVDNA==
    -----END CERTIFICATE-----
  auth-server.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDTM5WKBHr35cCc
    S4Iyt5U0QBqGI2qjVLy0IhDukdKpZoidLx8Zuk81xzfAQRhKWB+x99tAGFMULgg9
    b/4jMiU3cd2tUjKfsm43s8L0/+AlvpCCnWfCZde8RwN+khHt58+jWVoy8KjDMKgf
    KGo6Ueis1jBa5aQUgJCGiKqZyFVOIIPnhxr35sb0AkGkvvlv1568QIVZLh+W35Yo
    bSOvVKtUTvTjrJirpeUA1aEb8XERQVhDMH5R6/ggJD4mLkd9N6wL9EUFcfJahUKP
    yu3pAK6FpZTrVOMtIvtuFbifl9N1Cv5qw9bsLG0LC9QTGJ5l+d6aJGWzq117Hd7s
    FMaFt2BKs6kQvQu2T3D8Jr+8uW7XKTh4nwX7yoOngEJa1gYMhUcr2ZaDVm3+IHV+
    UqpmQDswSoX4z30jidGif3oddU9Q4tBdWnf3xwa4gnuGskPWxidcn2yshb1bLqIc
    KoMXNTMpmSqdZd+0sK3T0XL/TZVIN+MfjHZZdkNEFLackkqEZoqNiYByglHBAWiu
    KgKzFrkcnVvbrChDXLlnrealUPu9nf2xFW2OyXqtuR9BOhd+mEAt5/fhBOWKG0Tz
    E1VUVcXTMuDfbR1Gz9QjKgaQLEwxbsI59G7eFx6ByYRyU4KOCGKg9dNQ3PyTYqg5
    dwjpQmxl5aa4gnHyDXwbw1vWWy5/3QIDAQABAoICAAGTljKSvsnW7ZpWqsDu9q6O
    XYq4Y1vKW1Y+fHRFCZa5UzYiwekS2o1P0JS4zhIDMmL4f94TA5u+jdH9+551PPd6
    /Bw55T+kuO0Yt53VXLqRzGMmzz1314wD1uM8+xeuVH7adEscP/lx0lXZNJT9Q4iQ
    WLzbXF9izkr5MWM24Zwhr5pgCDPnHxkQyaVz+RZJCVnlljLVa04lZ4OJvQVA01gs
    kE6aw53Hl6JrKQOCYkVH5zBcZ+gvCla2SCVIA/SYhv1xdCQKqhp1RpfrYqpyMA6D
    VYDXZpK4FIeWPFIrDSluGZQTPil18285Ri38tkH6Nk7EP5YY817isph+JAIF6mWt
    rfcIeTXV068M+AeooUpxcJKRnB1atmnUdU0TlX2v8R6nGsjvllNlPzQE3xEPQhJs
    ijpOBvoFcJNE5WCg0NeG5OiNd6Pg6ky3q0MT2PydaQVaNSK1GkJJl9QMXPToh5qH
    Is1yFS5jH/nZbdSzg2UYPrmNGrO1YqUzTr1UF4khaaSsk16i8W8IwHRAhS5nUOGt
    xZd5VFv7uio3wc998qSMkkEGKpodkktRBfpXiPDTGNeH/hUWDGUOwsKAFYCXX+qQ
    ObbfxOV2zoUJCuIzJ07WvYVdDnOX3HwD5MSrmT27WKyw9ORrX95EZ+/ic/5kB1ga
    KH8DnCVvXgknq4uZeecBAoIBAQDxNR48pmtp/sKbLg9pxov2L+LiEY0XHHhdZtbl
    Vqrmhxkqh6rlwn7N3AEp0wJB5fiyts4ccAXuDN/Olnj0iTY7Y7CMBv17JI6cx9SQ
    k7iiou9h7Rl6LigmLuJnc3rgfAJwH6GyruekpOyqWvnff6tteUzZ4nH6UUOsh65Q
    EomX7yU0s35luAbg3dtmNazZZICnWHiqlcPqQ1lyaiuY/N18x8pA0fiws+rNC06v
    h0mgl1Aerggz4EjOSDZ2S60Y4s3t3Isre3IycmLTNq7ud6/a0Istqaf3yrfH5Ugt
    GImyqpHnEor67Kj3VYMLh9pRRuZsdjVW8xuHSgGZBh+0TeNhAoIBAQDgJ2GhjObt
    Biyk9Z0OsIYOFIMDWQezULZR/as/gvfKfqmySGM8GRYMX3jvIOYFfFE6h44z81gA
    I9cQAFv6CfRG6KxmhF5FTRwZNKpvGmuW1am4HVeuvjJ7hCi07d9fiqRduUC7PEbr
    0Y0JiZ1SZ1kos9HzICSPb7Td2nNe3LQwKh6JG6bq9GAFmSjp/A6PwjETEm8VVfHm
    jpMxNvSB65E1TcRII7T8TbpHSumWCGDnt2Y+64GrnUWCq0de3i4AIJfuANK/WFdi
    /VwYDt0JIR8r7rKpJL2ZUi3dNV8gLkrHKvTgStU7teK9esANyrdvFlu7BZ2yvODT
    gL43yJgvMmn9AoIBAQDNxKa6zq2riq2xfCWh8sLLjiZa/OYD5UG5TFXe54R7jJyn
    b30W7EkIjLphV6UBWpJCwzgpgldMsKbssekVk0g0eeLOUdhECPewP7jSbXKBK8ZT
    H9UwKdgOWsjBv/3/K0tZI2Lp79Ok3R0YZuvrAhrYFTa+WTMqe9DjigvmOyot9tEi
    mE0nsUoM4racBwYhnl8yY4Ls4z5yxmmz9Waj6HN6U2Xyziz9cT7JFPBXRW5GFU9A
    HO7acmcpsujjGcPdCv7p/86plXHiHzq3PFsXC/t1C5rvpV+pP8JwQOTFs70kMeat
    3V+6l9G8zbIxT/+qfnVr6ZuvRU0iqLucM2Ewi5GBAoIBAQCoCZ3NJ/3t7lUFjQMi
    gf7dC09z8QguyvEC4jHAuQPdj7rTZiTOZtf6io/0ZCtMLXgPcpOOKnzsDfIpkrtg
    5Jl1lvO3HsA1H6tS0gJ6q8nAF4jV91lGLFtX8Sk7CaAM1biGclwugO+B1WPvpHSF
    0+go9TUNGCmQRePG9P7MPJPwD4M4sbweIvjg+YKMdmLMLn3vmEAiNH3Vo0iA+nut
    8dS3qwbcNbh19CcTTvtxd/J9gyVpQc/BwXLclF46pkDB461BxOg4fZd1JA4oEuxs
    7aGao6TX3C0uhUbQsDQRweJZEMDma/MSgjXqad0T+cYtxwsZVwpzddjtdXQkCYLc
    zuRZAoIBAD4OeCe1R1M025pdOsMJB3ENX992UyPKAFcZWEIIXCRnrFq+OyckNvv/
    MzmiGpuNkyyeLpxlYU0QP+BsgQlM0/FLydYUPUXNLIgyqx4UfCKsaJoRw0f+9cmT
    fgaFp6o9tsB6Nu2OBINf0PErzwkXwscoUzUaiMq2lvMwGhke3mWnBXKHdZ4Fzv5k
    iEZ37A3S/iv7UvDEhNknmoENGSpTn/KfsUhQ4xWIOyt0vGQXDrx5j+vPg6jH9GyZ
    YYLMGfrLrRiomrH6jxMRHA9fZ9Eis7YQ2Yv/9k4otzgjr2STQPsrcRl4nHOrcFt5
    Eanz/UaaGkk1ddsIYH69GRL6sCjh3G4=
    -----END PRIVATE KEY-----
  auth-pubkey.pem: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0zOVigR69+XAnEuCMreV
    NEAahiNqo1S8tCIQ7pHSqWaInS8fGbpPNcc3wEEYSlgfsffbQBhTFC4IPW/+IzIl
    N3HdrVIyn7JuN7PC9P/gJb6Qgp1nwmXXvEcDfpIR7efPo1laMvCowzCoHyhqOlHo
    rNYwWuWkFICQhoiqmchVTiCD54ca9+bG9AJBpL75b9eevECFWS4flt+WKG0jr1Sr
    VE7046yYq6XlANWhG/FxEUFYQzB+Uev4ICQ+Ji5HfTesC/RFBXHyWoVCj8rt6QCu
    haWU61TjLSL7bhW4n5fTdQr+asPW7CxtCwvUExieZfnemiRls6tdex3e7BTGhbdg
    SrOpEL0Ltk9w/Ca/vLlu1yk4eJ8F+8qDp4BCWtYGDIVHK9mWg1Zt/iB1flKqZkA7
    MEqF+M99I4nRon96HXVPUOLQXVp398cGuIJ7hrJD1sYnXJ9srIW9Wy6iHCqDFzUz
    KZkqnWXftLCt09Fy/02VSDfjH4x2WXZDRBS2nJJKhGaKjYmAcoJRwQForioCsxa5
    HJ1b26woQ1y5Z63mpVD7vZ39sRVtjsl6rbkfQToXfphALef34QTlihtE8xNVVFXF
    0zLg320dRs/UIyoGkCxMMW7COfRu3hcegcmEclOCjghioPXTUNz8k2KoOXcI6UJs
    ZeWmuIJx8g18G8Nb1lsuf90CAwEAAQ==
    -----END PUBLIC KEY-----