apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-env
  namespace: gallery
data:
  USER_SERVICE_URL: "http://user-service:8080"
  AUTHENTICATION_DB_URL: "jdbc:postgresql://postgres-auth:5432/auth_db"
  REDIS_HOST: "redis"