apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: gallery
spec:
  serviceName: "kafka"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka-native:4.0.0
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - containerPort: 19092
            - containerPort: 9093
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          resources:
            requests:
              memory: "300M"
              cpu: "200m"
            limits:
              memory: "600M"
              cpu: "1000m"
          livenessProbe:
            tcpSocket:
              port: 19092
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 19092
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
      