apiVersion: v1
kind: ConfigMap
metadata:
  name: image-env
  namespace: gallery
data:
  COMMENT_SERVICE_URL: "http://comment-service:8080"
  USER_SERVICE_URL: "http://user-service:8080"
  IMAGES_DB_URL: "jdbc:postgresql://postgres-images:5432/images_db"
  REDIS_HOST: "redis"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:19092"
  AWS_URL_ENDPOINT: "http://localstack"
  AWS_REGION: "us-east-1"
