apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
        - name: image-service
          image: lubospodkidos/gallery-image-service:1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: image-env
            - secretRef:
                name: image-secrets
          env:
            - name: IMAGES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_IMAGES_USER
            - name: IMAGES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_IMAGES_PASSWORD
            - name: REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_USER
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_PASSWORD
          resources:
            requests:
              memory: "400M"
              cpu: "100m"
            limits:
              memory: "800M"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3