{{- range $secretName, $content := .Values.global_secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $secretName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "..labels" $ | nindent 4 }}
type: {{ $content.type | default "Opaque" }}
{{- if $content.files }}
data:
  {{- range $key, $path := $content.files }}
  {{ $key }}: {{ $.Files.Get $path | b64enc }}
  {{- end }}
{{- end }}
  {{- if $content.stringData }}
stringData:
  {{- toYaml $content.stringData | nindent 2 }}
  {{- end }}
{{- end }}