apiVersion: v1
kind: Secret
metadata:
  name: gateway-certs-secret
  namespace: gallery
type: Opaque
stringData:
  gateway-server.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFKDCCAxCgAwIBAgIUXWvocjLEDDShqIQWD/G2UyPsrFwwDQYJKoZIhvcNAQEL
    BQAwHTEbMBkGA1UEAwwSQXBpIEdhdGV3YXkgU2VydmVyMB4XDTI1MTIyNDEzMDE0
    NFoXDTI4MTAxMzEzMDE0NFowHTEbMBkGA1UEAwwSQXBpIEdhdGV3YXkgU2VydmVy
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtRWW73d9WdJPVAuVeMql
    XzB3719v/ruNo7zraMAp+/pw8jXQPs+6QVMRw0vobGDo4iull/5679ypiDmm9e7R
    qL9HL+cdi7Cl2yWLHM7G+SfaSkVNI+MrPxwEyvwY0QJAiFcIp/R7EWUnnhdgy/qA
    yVibbvTnn0oEYM7oLDEWR5d/OFH80JNZJRi6DbEZFPtYqxVRNRmkS5Xkxc/4m+TU
    4Amq4cjNsBpH68paVUI2ISn69tYmkbN/hA7vslXG5Jx6Y7jwqMWcTmtZb+4YJWMP
    sk5NFYaziC6EoIwaC+Sr4+zMB1VIAM3+Ckg1RyMC4Xi4spL0pnjvbGtvDpsFW93d
    Xii12aX6E9sBflne+lb+fn1n+d5w+uhF5yBQRxCb0uxRBXrxJVV/gkNVrP9y3UIM
    8LJ/weOxwPkbRjFpSA2Jp0hlVujY6POHZDKAabklpgEaTOR7TiPnSvZZ5EVBGLCh
    mUgZ4Ap1kfjSGUTa08beS8HrPHXyVI+dx6sCRvwfepky1I1f3xxeaJrdtbyluS9M
    beiwIQvPpjFfFdIEHoIpowkr4H356OKTEzz/P6OcIeIjryb21TUk2QedFYj8xxfC
    dWiwGEok0l7QYAYwU+Lt/Za7pZWWccv0DjMosNHdsYuYFK7Ougy0fRco/3jQHNHq
    iPmpcn+/tVCqvQUe8wTi+FUCAwEAAaNgMF4wHQYDVR0OBBYEFFEZmCCxYm6loJxG
    I6K3gpSHw7aqMB8GA1UdIwQYMBaAFFEZmCCxYm6loJxGI6K3gpSHw7aqMAwGA1Ud
    EwEB/wQCMAAwDgYDVR0PAQH/BAQDAgOoMA0GCSqGSIb3DQEBCwUAA4ICAQCXHb0i
    rjm7gX0efPHECjfgcScGhX6sbpZx7f8SZaF3ij8D0dKpY+S4dxCEPTBs6l0UHUpZ
    rjOk6dpF2LC6V3E+k+fbFqX4+VYzqww+RzmL4l20ksvaZYPlveymyvRKJuutxdYU
    FDJ6MM/SDVz7oQq5qIV2rts1y691xka+2DvYNQ9mNAwOZB/MHvqZJSGglNUJThpK
    5PVFEnncrCuPZcQTth0va8cYPPpx819gtN5DHs+BhzMyG0bTqU+lu4WZN0RLznbg
    WUpnNJB9AgoD4LPDdDa1cgN1zkM/gbwNHdaeN8lVnRnYD9qmn4f0Xj+4SpjT+O71
    +ZONowCkTmsulnRvoa903J1O34puZDPVc+Yx9qhFO+fUu7p92zvWUtLYOK7KgF7R
    BASpwpfQxRiIGJjp2QWWEmrA+EPxERIOQHH4gWNVlBaZhPVtFKuJJaY2OmPfRYDr
    p9g84rC/y6Qkf47lnpbth1nUkmmtytpq7tFTkBH746N/EBSpMPdDaLh/tNOycnJl
    SZZrcQZACMeQ588Mw4FSLKJ9QX0NaYN0xWv8k7d57FoO75pqlP4eKOP5gaRnSFE0
    d/+e6jFbMr7j41/stKPIZy8ogThB+39KT0MkUwWMXJbMC6hdk4EyUTy2SelGUbfi
    vF+hwZKpJa4PbSfqCn2v8qYNfsT48zOtPljCZQ==
    -----END CERTIFICATE-----
  gateway-server.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQC1FZbvd31Z0k9U
    C5V4yqVfMHfvX2/+u42jvOtowCn7+nDyNdA+z7pBUxHDS+hsYOjiK6WX/nrv3KmI
    Oab17tGov0cv5x2LsKXbJYsczsb5J9pKRU0j4ys/HATK/BjRAkCIVwin9HsRZSee
    F2DL+oDJWJtu9OefSgRgzugsMRZHl384UfzQk1klGLoNsRkU+1irFVE1GaRLleTF
    z/ib5NTgCarhyM2wGkfrylpVQjYhKfr21iaRs3+EDu+yVcbknHpjuPCoxZxOa1lv
    7hglYw+yTk0VhrOILoSgjBoL5Kvj7MwHVUgAzf4KSDVHIwLheLiykvSmeO9sa28O
    mwVb3d1eKLXZpfoT2wF+Wd76Vv5+fWf53nD66EXnIFBHEJvS7FEFevElVX+CQ1Ws
    /3LdQgzwsn/B47HA+RtGMWlIDYmnSGVW6Njo84dkMoBpuSWmARpM5HtOI+dK9lnk
    RUEYsKGZSBngCnWR+NIZRNrTxt5Lwes8dfJUj53HqwJG/B96mTLUjV/fHF5omt21
    vKW5L0xt6LAhC8+mMV8V0gQegimjCSvgffno4pMTPP8/o5wh4iOvJvbVNSTZB50V
    iPzHF8J1aLAYSiTSXtBgBjBT4u39lrullZZxy/QOMyiw0d2xi5gUrs66DLR9Fyj/
    eNAc0eqI+alyf7+1UKq9BR7zBOL4VQIDAQABAoICAAl3f6S06vqLT6FgWlKZHtcg
    n2Hba+1LHHxZuowx4PVZjOu6BiaFJpgWrIA4vjBi9UR/AqZfuUlD5csHiePOi0Bs
    AN/kuxCGo3fBo98ALQ/GgRd5Pa9UHM/XpPqAU8Mi1SvWMk98LQOQ9bwX6HQRfF0f
    rZSPPMgA5G9ehxhprTVV8A004BIpZIjXckFCp8HcjVtNqdQBq1YA7UJYJ9ztNCHN
    mj+Oh2Oe+XE+wBqNSRYnwy/XVzyDv/VamzZdXKCupjQDbaAXy0mgPBSUGR1kleP8
    9Z5b+ekd1sor44qz9uEwtnk7AKDQzr32iMPXdTruBuiIXT48u/Y/kZaXt8qAiVDg
    XbsbSywpxdapRRpw17emBw9iGEzeoG5qkrdRj/P2yYh6kQU6E03ku3GKbvfUimb9
    x0k3nqIsNROBMQz+rVk1pJylBQ7XxSIvj/KJMNXhpdb6Jvku4SfEQ/3hri9wSDHQ
    CYGedc1l+DhSc22+w9biKcS0l1PKZcytPKAwDvG8CNUDB1QaeZ0NLtBoZr8licG8
    k996aKWjcCbdlwR+d8JY5VULEYRTIsY7ej3BbntYUw3C5Tb14vYzS4v6AlTeLLyl
    /7R+0V+Th3LHZ5C+ZGmn05bA3Vi5/z+IhN1onyzOA+R/6ULhm36XQ+8E050xhBi3
    fHwD6PfpT0u+x5Vv3K4LAoIBAQDxSXSOeCM+nvOwDB26KbbDXwUqr7tAbcsjeadQ
    IkwSmikyOvfaCrkILP3KRrVtUIr6nk1V0LqtjeAyd8hTuofaE30OlNITfPOLxcD7
    Esv1HtDWnSyzkYNVo+ubDV9fLHU2oMLA9Bg5tHcgGSf44qT1TqM4wekwgZJS87J4
    5SR7QFZ9rc31UtNBnyii6anSo24kIbHIv7XYlWSfuSlcWxu1qtmSu7FgJ9F7e0rY
    pQNxNG2es4PQO0P9/aDZKPyHRSwCyAMm8yJa/I9NNjXVu37vAsMFVyCiZg4Ry698
    HU36ADNVxYVHi2KegVHdbspBbOC2vDFXbjeM+Vkz6/4NE+EfAoIBAQDAIFuZxZnq
    eos6ZdS1egWmh7kzpdRTwBJMeqDG8Ul5xnT3CzLRR/taN4VJe6MRJ2FVbhbgQWce
    N3SlTR2QtnyE4sJ0qGXENa5HptBbsNCe+cG3xSY+iNCAFs8IkTamQPeq9ajQp05z
    kODR8vVmoLUVNwC/dZsM5mezsJOju7cqi30c4goLQinnxMCXPRikqMEg04VLpUYb
    AseeeEfpoGQVper7PaoXmcRSNf6OQDLKqtTxwXEqyWvsQ8SFHWLkJ4wd9oqIKW0y
    z7hZqNls3QM2vbxcT2Mk2WopYNigY74mwVLGCBahfdHssR8PlVNTqQoJoIr2gb+L
    1l8qoCrk8jQLAoIBAQCNRSe0HozsJh6hbYaeL7wtCV46DufAokf0fk7CsUH/Bjmm
    ijYBeJO7QLRbESk6VpT4hWTcILib0tx4T/9/XlAaE5z9w454EIl7xY3msqut2ZwG
    e8HnZQQTSUUx5BN54srB8D/2vzPL3Wh955yqsPBKG/+exJHmb4afgMV22RqR+ypo
    rTFQOG0uF6SwNcTTahKbnwq7cdtjcpyWk8+unj1METsQGUqR9N5GwPoifALW7g5c
    g9hiO8DkXfImE0Q/YvWQr1CBJotv4D16xImimQOJpwFOCCQ4US5dpvcY4QN9o05r
    IpmVOPvFuAuZbTuIMNokw2zUNtjZdkiPCNYXDBObAoIBADRbnRr24s8nvjGX9rPO
    ISQU8L/GfWqleVcmRBJzRxbMoquAfcTS3QjlAInaC8Js/PWPHuTWbgeqDTvPHDOH
    x79fHKc2DSW/i1Mzfqy+LtxkLAqsy5NXLZr6nEk1abM9GUGZ2Puj3JlZ7irJD198
    hFzXtHh40Fxfnfs2L8X7LhuGD/6DC0GuMkVbNTECEWkuJBOSEU1gKQ7LXyMsnExq
    zVuo77SwRV5RJVNSK6EQlcbtb0LC+Ng0NBkbDr9IFt8ed+zidzZMM9oZCaBFh5tH
    T8znQCHX8KjmJyxHnEF5bSSaorgdFC3GYCMk0dYpV6AA/R9KhRRQn6a4MQ8ovwfN
    iakCggEAPczrNatxQ/v1/4ubZtQKNvNO5vaZ4rWBM79zYyYnqs6u3vjgV+xOV3w+
    tAjsGoy6D337rSjBmQ6Al0NFoPKonvyoQ13xLSu7noBOWvjDacFid9DQBfP000cM
    i3CHo7215/OQgDJ8sHL5bXu76aAdkhE4YcNTBzWIiXhkX3/iHpEM80JgwN7XeVfg
    G2YHortyAQCJbfnBQiQxGkOp3w/qlPVubBwoq715pBKsE2Wk5w0qUU3t5Zf6yQgI
    xmKxZjafOhe2kTTXk6t29hLhy1bEQgM1AZKPRSs9LgImsPKAnVXl1eguyW05fZJT
    aIiIuCTkigAAEddtXk8RVEHHOl3+dA==
    -----END PRIVATE KEY-----