apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: gallery
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:8.2
          command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            - name: config
              mountPath: /etc/mongo
          resources:
            requests:
              memory: "250M"
              cpu: "100m"
            limits:
              memory: "500M"
              cpu: "500m"
          livenessProbe:
            exec:
              command: ["sh", "/etc/mongo/healthcheck.sh"]
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["sh", "/etc/mongo/healthcheck.sh"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: config
          configMap:
            name: mongo-config
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi