apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-setup-job
  namespace: gallery
spec:
  template:
    spec:
      containers:
        - name: setup
          image: mongo:8.2
          command: ["bash", "/scripts/replica-setup.sh"]
          volumeMounts:
            - name: config
              mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
        - name: config
          configMap:
            name: mongo-config
            defaultMode: 0755
  