serviceName: redis

image:
  repository: redis
  tag: "8-alpine"

env:
  - name: REDIS_USER
    valueFrom:
      secretKeyRef:
        { name: '{{ .Release.Name }}-redis-secret' , key: REDIS_USER }
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        { name: '{{ .Release.Name }}-redis-secret' , key: REDIS_PASSWORD }
  - name: REDIS_DEFAULT_PASSWORD
    valueFrom:
      secretKeyRef:
        { name: '{{ .Release.Name }}-redis-secret' , key: REDIS_DEFAULT_PASSWORD }

files:
  - src: "conf/entrypoint.sh"
    dest: "entrypoint.sh"
  - src: "conf/redis.template.conf"
    dest: "redis.template.conf"
  - src: "conf/users.template.acl"
    dest: "users.template.acl"

storage:
  name: redis-data
  path: /data
  size: 1Gi

volumeMounts:
  - name: config-templates
    mountPath: /app/redis

volumes:
  - name: config-templates
    configMap:
      name: config

containerPort: 6379

service:
  create: true
  headless: true

command: ["sh", "/app/redis/entrypoint.sh"]

probe:
  liveness:
    livenessProbe:
      exec:
        command: ["redis-cli", "ping"]
    initialDelaySeconds: 15
  readiness:
    readinessProbe:
      exec:
        command: ["redis-cli", "ping"]
    initialDelaySeconds: 10

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"