apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-env
  namespace: gallery
data:
  SERVICES: "s3"
  PERSIST_DEFAULT: "0"
  PERSIST_S3: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-init-config
  namespace: gallery
data:
  init-aws-s3.sh: |
    #!/bin/bash
    set -e
    echo "Initializing S3 bucket 'images'"
    awslocal s3 mb s3://images
    echo "S3 bucket 'images' created successfully."
