apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-config
  namespace: gallery
data:
  dynamic_config.yaml: |
    auth:
      type: DISABLED
    kafka:
      clusters:
        - bootstrapServers: kafka:19092
          name: galleryCluster
          properties: {}
          readOnly: false
    rbac:
      roles: []
    webclient: {}